storage:
  address: 192.168.0.11:9000
  accessKey: UNWNNGRKK2XWK6IZ1HVZ
  secretKey: CLROgFMJlsMFDEojwQgpC43dsr+0+BRzOTz1DbqN
  live: e:/data/live
  recording: e:/data/record
bind-address: 0.0.0.0:8000
timezone: Asia/Seoul
static:
  dir: E:/gohome/src/github.com/devplayg/rtsp-stream-ui/static
